platform :ios, '9.0'
# use_frameworks!
inhibit_all_warnings!

target 'Mall' do
  
  pod 'CYLTabBarController', '~> 1.24.0'
  # OC风格自动布局 参考https://www.jianshu.com/p/f8d1a660ec30
  pod 'PureLayout', '~> 3.1.4'
  pod 'AFNetworking', '~> 3.0'
  # pod 'SVProgressHUD', '~> 2.2.5'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.1.16'
  pod 'MJExtension', '~> 3.1.0'
  pod 'TYPagerController', '~> 2.1.2'
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDCycleScrollView','~> 1.80'
  # 主要为了解决网络请求返回json 含有NSNull问题
  pod 'NullSafe', '~> 2.0'
  # 资源选择
  # pod 'ZLPhotoBrowser'
  pod 'TZImagePickerController', '~> 3.2.1'
  # 圆形头像裁剪
  pod 'TOCropViewController', '~> 2.5.1'
  # 图片浏览 SDWebImage问题
  # pod 'LBPhotoBrowser', '~> 2.2.2'
  # pod 'YBImageBrowser', '~> 3.0.3'
  # 数据库
  pod 'FMDB', '~> 2.7.5'
  # 为了低于iOS 9系统可以使用
  pod 'FDStackView', '~> 1.0.1'
  
  # h5秒开方案 腾讯X5内核
  pod 'VasSonic', '~> 3.1.1'

  # mmap 键值保存的方式
  pod 'MMKV', '~> 1.0.22'
  
  # 主要是c语言方法的钩子
  pod 'fishhook'
  
  # 日志打印
  pod 'CocoaLumberjack', '~> 3.5.3'
  
  pod 'GZIP', '~> 1.2'
  
  target 'MallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# 第三方框架 deployment target  警告的问题
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f <= 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

# 瀑布流：https://github.com/wslcmk/waterFlow.git
# h5秒开优化：https://juejin.im/post/5d8da122f265da5b5a7209fa
# iOS13适配：https://juejin.im/post/5d85c3fde51d453b7779d604
# 向上滑动头部锁定： https://github.com/pujiaxin33/JXPagingView
# 仿系统通知样式通知栏：https://github.com/pikacode/EBBannerView
# 自定义弹窗：https://github.com/JonyFang/FFPopup.git
# 在线网站：http://www.cocoachina.com/articles/53437?filter=rec
# CardView: http://www.cocoachina.com/articles/35486
# Logo和启动图尺寸：https://www.jianshu.com/p/12f1c21b6613 图标工厂：https://icon.wuruihong.com
# iOS 13适配技巧：https://github.com/ChenYilong/iOS13AdaptationTips
# 免费UI调试工具：https://lookin.work
# 导航栏间距：https://github.com/spicyShrimp/UINavigation-SXFixSpace
# 树形结构：https://github.com/wsl2ls/MultilevelList
# 设备支持包：https://github.com/iGhibli/iOS-DeviceSupport/tree/master/DeviceSupport
# 输入框自定义键盘：https://github.com/cgmsuccess/CustomKeyBoard
