platform :ios, '9.0'
# use_frameworks!
inhibit_all_warnings!

source "https://github.com/CocoaPods/Specs.git"

target 'Mall' do
  
  pod 'CYLTabBarController', '~> 1.28.3'
  # OC风格自动布局 参考https://www.jianshu.com/p/f8d1a660ec30
  pod 'PureLayout', '~> 3.1.4'
  pod 'AFNetworking/Serialization', '~> 3.2.1'
  pod 'AFNetworking/Security', '~> 3.2.1'
  pod 'AFNetworking/Reachability', '~> 3.2.1'
  pod 'AFNetworking/NSURLSession', '~> 3.2.1'
  # pod 'SVProgressHUD', '~> 2.2.5'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.1.16'
  pod 'MJExtension', '~> 3.1.0'
  pod 'TYPagerController', '~> 2.1.2'
  pod 'YYImage', '~> 1.0.4'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDCycleScrollView','~> 1.80'
  # 主要为了解决网络请求返回json 含有NSNull问题
  pod 'NullSafe', '~> 2.0'
  # 资源选择
  # pod 'ZLPhotoBrowser'
  pod 'TZImagePickerController', '~> 3.2.1'
  # 圆形头像裁剪
  pod 'TOCropViewController', '~> 2.5.1'
  # 图片浏览 SDWebImage问题
  # pod 'LBPhotoBrowser', '~> 2.2.2'
  # pod 'YBImageBrowser', '~> 3.0.3'
  # 数据库
  pod 'FMDB', '~> 2.7.5'
  # 为了低于iOS 9系统可以使用
  pod 'FDStackView', '~> 1.0.1'
  
  # mmap 键值保存的方式
  pod 'MMKV', '~> 1.0.22'
  
  # 主要是c语言方法的钩子
  pod 'fishhook'
  
  # 日志打印
  pod 'CocoaLumberjack', '~> 3.5.3'
  
  pod 'GZIP', '~> 1.2'
  
  # 扫码
  pod 'LBXScan/LBXNative','~> 2.3'
  pod 'LBXScan/LBXZXing','~> 2.3'
  # pod 'LBXScan/LBXZBar','~> 2.3'
  pod 'LBXScan/UI','~> 2.3'
  
  # 内存泄漏检测
  pod 'MLeaksFinder'
  # 内存占用检测
  pod 'FBMemoryProfiler'
  
  target 'MallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# 第三方框架 deployment target  警告的问题
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f <= 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

# LLDB调试利器和高级用法：https://www.jianshu.com/p/c91f843a64fc
# sign in apple: https://www.jianshu.com/p/483b998f2370 https://www.jianshu.com/p/e1284bd8c72a
# linkMap: 检查每个类占用大小 https://github.com/huanxsd/LinkMap   https://techblog.toutiao.com/2016/12/27/iphone/
# iOS瘦身之删除FrameWork中无用mach-O文件 https://www.infoq.cn/article/ios-thinning-delete-unnecessary-mach-o/
# 滴滴出行包体积优化：https://ming1016.github.io/2017/06/12/gmtc-ios-slimming-practice/
# feed流优化：https://github.com/liangdahong/UITableView-BMDynamicLayout
# 保存长截图：https://github.com/TonyReet/TYSnapshotScroll
# 瀑布流：https://github.com/wslcmk/waterFlow.git
# h5秒开优化：https://juejin.im/post/5d8da122f265da5b5a7209fa
# iOS13适配：https://juejin.im/post/5d85c3fde51d453b7779d604
# 向上滑动头部锁定： https://github.com/pujiaxin33/JXPagingView
# 扫描二维码：https://github.com/wsl2ls/ScanQRcode
# 仿系统通知样式通知栏：https://github.com/pikacode/EBBannerView
# 自定义弹窗：https://github.com/JonyFang/FFPopup.git、https://github.com/choiceyou/FWPopupView
# 在线网站：http://www.cocoachina.com/articles/53437?filter=rec
# CardView: http://www.cocoachina.com/articles/35486
# Logo和启动图尺寸：https://www.jianshu.com/p/12f1c21b6613 图标工厂：https://icon.wuruihong.com
# iOS 13适配技巧：https://github.com/ChenYilong/iOS13AdaptationTips
# 免费UI调试工具：https://lookin.work
# 导航栏间距：https://github.com/spicyShrimp/UINavigation-SXFixSpace
# 树形结构：https://github.com/wsl2ls/MultilevelList
# 设备支持包：https://github.com/iGhibli/iOS-DeviceSupport/tree/master/DeviceSupport
# 输入框自定义键盘：https://github.com/cgmsuccess/CustomKeyBoard
# 扩大自带手势范围和解决UIScrollView手势冲突的问题：https://gitee.com/aiwoba/BFBaseFrameworkKit/blob/swift4_0/Swift_baseFramework/Swift_baseFramework/BaseFrameworkKit/Main/BFPanBaseNavigationViewController.swift
# 拖拽重排：https://github.com/liangdahong/BMLongPressDragCellCollectionView 、https://github.com/lizelu/CESelectThemes
# iOS13适配：https://www.jianshu.com/p/d2a0fa7bcbef
# LLDB调试：https://www.jianshu.com/p/c91f843a64fc
# 侧滑菜单: https://github.com/choiceyou/FWSideMenu
# 无网络占位：https://github.com/dev-liyang/LYEmptyView
# 图片下载封装：https://github.com/ripeyd/ZYImageCache
# pickView: https://github.com/91renb/BRPickerView
# 分类文件集合：https://github.com/shaojiankui/JKCategories
# 个人中心：https://github.com/ArchLL/HGPersonalCenter
# MJRefresh 定制方案: https://www.jianshu.com/p/df1f1f265c33
# webp导入：https://www.jianshu.com/p/7a3dd76004db
